name: ↔️ Connector Request
description: Request a new connector.
labels: [connector, triage]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the feature you want to request.
    options:
    - label: I have searched the existing issues
      required: true
- type: input
  attributes:
    label: Resource name
    description: Name of the resource this connector would read data from/to.
    placeholder: Elasticsearch
  validations:
    required: true
- type: input
  attributes:
    label: Resource link
    description: Link to the official page of this resource (source code repository if it's open source).
    placeholder: https://github.com/elastic/elasticsearch
  validations:
    required: true
- type: dropdown
  attributes:
    label: Connector type
    options:
      - source
      - destination
- type: textarea
  attributes:
    label: Expected connector behavior
    description: A clear and concise description of how you expect this connector to work.
    placeholder: Each time a document is created on Elasticsearch a new record should be pushed into the pipeline [...]
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the connector you want to see!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
