name: 🔁 Connector Request
description: Request a new connector.
title: "Connector: <resource> [Source/Destination]"
labels: [connector, triage]
body:
- type: checkboxes
  attributes:
    label: Is there an open request for this connector?
    description: Please search to see if an issue already exists for the connector you want to request.
    options:
    - label: I have searched the existing issues
      required: true
- type: input
  attributes:
    label: Resource name
    description: Name of the resource this connector would read data from/to.
    placeholder: PostgreSQL
  validations:
    required: true
- type: input
  attributes:
    label: Resource link
    description: Link to the official page of the resource.
    placeholder: https://www.postgresql.org/
  validations:
    required: true
- type: dropdown
  attributes:
    label: Connector type
    options:
      - Source
      - Destination
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected connector behavior
    description: A clear and concise description of how you expect this connector to work.
    placeholder: The connector should take a list of tables and detect inserts, updates and deletes [...]
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the connector you want to see!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
